# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0e9cb3f609f9ae37895f2c3bc85c5abf0e5ea55f6574e12713bfb5ccc679efa2728aee4efe3dfde1d8742204404c32b3efb9c5d7830db7be45632e4f7175c11

test:
  secret_key_base: 295ec3c1a8ea9cf7a25b28ea77101399dea593838a4e3d7ed881c18e519ae3018d25891e6c7298ccf5a6c6b79b26e75e0c9f423e01cff909f137322c4549c23b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
